spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 514342237226-6kf495bld2ud832b5tesqsugokvcidf9.apps.googleusercontent.com
            client-secret: lRK6c9PHmTZDnMaPTvgcHRhE
          facebook:
            client-id: 1048731185333188
            client-secret: 8d9815e3951dff92140e91408f15910e


  datasource:
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/principal
    username: root
    password: 1111
  level:
    org.springframework.security: DEBUG

cors:
  origin: "http://localhost:4200"

management:
  endpoints:
    web:
      exposure:
        include: ['*']

server:
  port: 8080

google.storage: 'C:\projects\creds\PotenkoProject-139e858a53e7.json'