spring:
  session:
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION
    store-type: jdbc
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 514342237226-6kf495bld2ud832b5tesqsugokvcidf9.apps.googleusercontent.com
            client-secret: lRK6c9PHmTZDnMaPTvgcHRhE
          facebook:
            client-id: 1048731185333188
            client-secret: 8d9815e3951dff92140e91408f15910e
            scope: ["public_profile", "email"]


  datasource:
    driver-class-name=com: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable
    username: postgres
    password: 1111
  level:
    org.springframework.security: DEBUG


cors:
  origin: "http://localhost:4200"

management:
  endpoints:
    web:
      exposure:
        include: ['*']

server:
  port: 8080
  servlet:
    session:
      timeout: '1440m'

app.url: "http://localhost:4200/welcome"

google.storage: 'C:\projects\creds\PotenkoProject-139e858a53e7.json'
